// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import model_1 from '/Users/xiaodingyang/肖定阳的文档/项目文档/myblog/frontend/src/models/articleModel';
import model_2 from '/Users/xiaodingyang/肖定阳的文档/项目文档/myblog/frontend/src/models/categoryModel';
import model_3 from '/Users/xiaodingyang/肖定阳的文档/项目文档/myblog/frontend/src/models/colorModel';
import model_4 from '/Users/xiaodingyang/肖定阳的文档/项目文档/myblog/frontend/src/models/messageModel';
import model_5 from '/Users/xiaodingyang/肖定阳的文档/项目文档/myblog/frontend/src/models/particleModel';
import model_6 from '/Users/xiaodingyang/肖定阳的文档/项目文档/myblog/frontend/src/models/tagModel';
import model_7 from '/Users/xiaodingyang/肖定阳的文档/项目文档/myblog/frontend/src/models/userModel';
import model_8 from '/Users/xiaodingyang/肖定阳的文档/项目文档/myblog/frontend/src/.umi-production/plugin-initialState/@@initialState';

export const models = {
model_1: { namespace: 'articleModel', model: model_1 },
model_2: { namespace: 'categoryModel', model: model_2 },
model_3: { namespace: 'colorModel', model: model_3 },
model_4: { namespace: 'messageModel', model: model_4 },
model_5: { namespace: 'particleModel', model: model_5 },
model_6: { namespace: 'tagModel', model: model_6 },
model_7: { namespace: 'userModel', model: model_7 },
model_8: { namespace: '@@initialState', model: model_8 },
} as const
