// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","id":"1"},"2":{"path":"/","parentId":"1","id":"2"},"3":{"path":"/articles","parentId":"1","id":"3"},"4":{"path":"/article/:id","parentId":"1","id":"4"},"5":{"path":"/categories","parentId":"1","id":"5"},"6":{"path":"/category/:id","parentId":"1","id":"6"},"7":{"path":"/tags","parentId":"1","id":"7"},"8":{"path":"/tag/:id","parentId":"1","id":"8"},"9":{"path":"/about","parentId":"1","id":"9"},"10":{"path":"/message","parentId":"1","id":"10"},"11":{"path":"/admin/login","id":"11"},"12":{"path":"/admin","id":"12"},"13":{"path":"/admin","redirect":"/admin/dashboard","parentId":"12","id":"13"},"14":{"path":"/admin/dashboard","parentId":"12","id":"14"},"15":{"path":"/admin/articles","parentId":"12","id":"15"},"16":{"path":"/admin/articles/create","parentId":"12","id":"16"},"17":{"path":"/admin/articles/edit/:id","parentId":"12","id":"17"},"18":{"path":"/admin/categories","parentId":"12","id":"18"},"19":{"path":"/admin/tags","parentId":"12","id":"19"},"20":{"path":"/admin/messages","parentId":"12","id":"20"},"21":{"path":"/admin/settings","parentId":"12","id":"21"},"22":{"path":"/*","id":"22"}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import(/* webpackChunkName: "layouts__FrontLayout" */'@/layouts/FrontLayout.tsx')),
'2': React.lazy(() => import(/* webpackChunkName: "p__home__index" */'@/pages/home/index.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__articles__index" */'@/pages/articles/index.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__articles__detail" */'@/pages/articles/detail.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__categories__index" */'@/pages/categories/index.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__categories__detail" */'@/pages/categories/detail.tsx')),
'7': React.lazy(() => import(/* webpackChunkName: "p__tags__index" */'@/pages/tags/index.tsx')),
'8': React.lazy(() => import(/* webpackChunkName: "p__tags__detail" */'@/pages/tags/detail.tsx')),
'9': React.lazy(() => import(/* webpackChunkName: "p__about__index" */'@/pages/about/index.tsx')),
'10': React.lazy(() => import(/* webpackChunkName: "p__message__index" */'@/pages/message/index.tsx')),
'11': React.lazy(() => import(/* webpackChunkName: "p__admin__login" */'@/pages/admin/login.tsx')),
'12': React.lazy(() => import(/* webpackChunkName: "layouts__AdminLayout" */'@/layouts/AdminLayout.tsx')),
'13': React.lazy(() => import('./EmptyRoute')),
'14': React.lazy(() => import(/* webpackChunkName: "p__admin__dashboard__index" */'@/pages/admin/dashboard/index.tsx')),
'15': React.lazy(() => import(/* webpackChunkName: "p__admin__articles__index" */'@/pages/admin/articles/index.tsx')),
'16': React.lazy(() => import(/* webpackChunkName: "p__admin__articles__create" */'@/pages/admin/articles/create.tsx')),
'17': React.lazy(() => import(/* webpackChunkName: "p__admin__articles__edit" */'@/pages/admin/articles/edit.tsx')),
'18': React.lazy(() => import(/* webpackChunkName: "p__admin__categories__index" */'@/pages/admin/categories/index.tsx')),
'19': React.lazy(() => import(/* webpackChunkName: "p__admin__tags__index" */'@/pages/admin/tags/index.tsx')),
'20': React.lazy(() => import(/* webpackChunkName: "p__admin__messages__index" */'@/pages/admin/messages/index.tsx')),
'21': React.lazy(() => import(/* webpackChunkName: "p__admin__settings__index" */'@/pages/admin/settings/index.tsx')),
'22': React.lazy(() => import(/* webpackChunkName: "p__404" */'@/pages/404.tsx')),
},
  };
}
